title: Cansu Demir
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cannsudemir.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: '/:title/'
collections: 
  posts:permalink: '/posts/:title/'
header:
  title: Cansu Demir
  tagline: Minimal and clean blog theme
  logo_img: images/logo1.png
  bg_img: images/11.jpeg
  has_nav: true
  has_social: true
footer:
  content: '&copy; All rights reserved. Theme by John Doe'
  
palette: yellow
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
include:
  - static
